### ISSUE TITLE
Magic++.h error

### ISSUE THREAD

**Issue by malani-art** [DIYCharles/RGBGIFSlideshow#1]
Hey, when I run the command "sudo make led-image-viewer", I get this error message from the terminal:

~/rpi-rgb-led-matrix/utils $ sudo make led-image-viewer
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64 `GraphicsMagick++-config --cppflags --cxxflags` -c -o led-image-viewer.o led-image-viewer.cc
/bin/sh: 1: GraphicsMagick++-config: not found
led-image-viewer.cc:42:10: fatal error: Magick++.h: No such file or directory
 #include <Magick++.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:37: led-image-viewer.o] Error 1

Any idea why I get this? I tried installing it with sudo apt-get install libmagick++-dev but I still get this error...

**Comment by malani-art** [comment]
I tried ignoring this step and proceeding. However, I have also been receiving these errors:

pi@xyz:~ $ cd /home/pi/gifs
pi@xyz:~/gifs $ sudo /home/pi/gifs/gifscript
1
{GIF 1}
sudo: /home/pi/rpi-rgb-led-matrix/utils/led-image-viewer: command not found
/home/pi/gifs/gifscript: line 12: wait: pid 1 is not a child of this shell
{GIF 2}
sudo: /home/pi/rpi-rgb-led-matrix/utils/led-image-viewer: command not found

**Comment by giantmolecules** [comment]
Try installing graphicsmagick-libmagick-dev-compat
